# .NET Core Function App to Windows on Azure
# Build a .NET Core function app and deploy it to Azure as a Windows function App.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/en-us/azure/devops/pipelines/languages/dotnet-core

trigger:
- '*'

variables:
  # Agent VM image name
  vmImageName: 'vs2017-win2016'

jobs:
- job: Build
  displayName: 'Unit tests, build, archive, '
  pool:
    vmImage: $(vmImageName)

  steps:
  - task: DotNetCoreCLI@2
    inputs:
      command: 'restore'
      projects: '**/*.sln'
      feedsToUse: 'select'
      vstsFeed: '86f41d1b-d3bf-45d4-b7b5-74afb83bee1c/51986b3a-cec9-4ea0-b981-37c12e2d9b2e'

  - task: DotNetCoreCLI@2
    displayName: Run unit Tests for BookReadingRepository
    inputs:
      command: 'test'
      projects: 'BookReadingRepositoryUnitTest'

  - task: DotNetCoreCLI@2
    displayName: Build
    inputs:
      command: 'build'
      projects: 'BookReadingRepository'
      arguments: --output $(System.DefaultWorkingDirectory)/publish_output --configuration Release

  - task: ArchiveFiles@2
    displayName: 'Archive executables'
    inputs:
      rootFolderOrFile: '$(System.DefaultWorkingDirectory)/publish_output'
      includeRootFolder: false
      archiveType: zip
      archiveFile: $(Build.ArtifactStagingDirectory)/BookReadingRepository-$(Build.BuildId).zip
      replaceExistingArchive: true

  - publish: $(Build.ArtifactStagingDirectory)/BookReadingRepository-$(Build.BuildId).zip
    displayName: publish executables
    artifact: drop

  - task: ArchiveFiles@2
    displayName: 'Archive solution'
    inputs:
      rootFolderOrFile: '$(System.DefaultWorkingDirectory)'
      includeRootFolder: false
      archiveType: zip
      archiveFile: $(Build.ArtifactStagingDirectory)/BookReading.zip
      replaceExistingArchive: true

  - publish: $(Build.ArtifactStagingDirectory)/BookReading.zip
    displayName: publish solution
    artifact: solution
